class BKTree:
    def __init__(self) -> None: ...
    def add(self, x: int) -> bool: ...
    def any_within(self, x: int, radius: int) -> bool: ...
    def find_all_within(self, x: int, radius: int) -> list[int]: ...
    def __len__(self) -> int: ...

class UnionFind:
    def __init__(self) -> None: ...
    def make_set(self, x: int) -> None: ...
    def find(self, x: int) -> int: ...
    def union(self, a: int, b: int) -> None: ...
    @property
    def component_count(self) -> int: ...

class CoverageTracker:
    def __init__(self, radius: int) -> None: ...
    def add_hash(self, x: int) -> bool: ...
    @property
    def coverage_count(self) -> int: ...
    @property
    def total_unique(self) -> int: ...
    def reset(self) -> None: ...
